### ISSUE TITLE
Document GitHub User Search Requirements

### ISSUE THREAD

**Issue by clintonb** [gocd-contrib/gocd-oauth-login#32] opened 2016-02-02 16:41 UTC
GitHub user search only works if you setup the plugin with a username and password/OAuth token. Please document this fact.

**Comment by arvindsv** [comment] 2016-05-24 17:05
I'm not the author, but I think I might have permissions to accept PRs. If you want to improve the README and submit a PR for it, I'll accept it.

**Comment by pedrocarrico** [comment] 2017-02-13 15:57
Even with an OAuth token with access to the organization I can't seem to search in GitHub and I don't see anything in the logs. Is it possible to add more logging?

**Comment by mathieulj** [comment] 2017-02-14 13:29
Im having the same issue as @pedrocarrico with gitlab ce. GoCD can authenticate idividual users (I assume) since they can do the whole procedure and then a log item shows up saying that an admin must add them first. However, the user search does not populate with OAUTH users and nothing is shown in the log.

**Comment by varshavaradarajan** [comment] 2017-02-14 14:13
@pedrocarrico , @mathieulj - This was an issue with gocd's core code. It has been fixed with https://github.com/gocd/gocd/pull/3107/commits/7ddf84eaaf813546aa1f8eb684ef9cf3187f6617. You can verify the fix with the experimental build provided [here](https://www.gocd.io/download/?experimental=true)

**Comment by pedrocarrico** [comment] 2017-02-14 14:36
Thanks @varshavaradarajan !

**Comment by pedrocarrico** [comment] 2017-04-20 17:43
I can confirm that with the latest GoCD version 17.3 and version 2.3 of this plugin this doesn't happen anymore.

You can probably close this issue.

**Comment by ketan** [comment] 2017-04-21 07:32
@pedrocarrico thank you for confirming. Closing issue

**Closed as completed by ketan** 2017-04-21 07:32 UTC

**Comment by varshavaradarajan** [comment] 2017-04-21 09:54
We need to still add to the documentation that for searching, you'd need to provide username and password/oauth token.
